from pydantic import BaseModel, EmailStr, Field
from typing import Optional
from datetime import datetime
from uuid import UUID

# --- User Schemas ---

class UserCreate(BaseModel):
    email: EmailStr
    auth_hash_derived: str = Field(..., description="The hash derived from Master Password for Auth (Client derived)")
    kdf_salt: str = Field(..., description="Random salt generated by client for KDF")
    encrypted_dek: str = Field(..., description="The Data Encryption Key encrypted by the KEK")

class UserLogin(BaseModel):
    email: EmailStr
    auth_hash_derived: str

class UserRotateKey(BaseModel):
    auth_hash_derived: str = Field(..., description="The new hash derived from New Master Password")
    kdf_salt: str = Field(..., description="New random salt")
    encrypted_dek: str = Field(..., description="The Data Encryption Key re-encrypted by the new KEK")

class UserResponse(BaseModel):
    id: UUID
    email: EmailStr
    kdf_salt: str
    encrypted_dek: str
    created_at: datetime
    
    class Config:
        from_attributes = True

class Token(BaseModel):
    access_token: str
    token_type: str
    user: UserResponse

# --- Vault Schemas ---

class VaultItemBase(BaseModel):
    type: str = Field(..., pattern="^(login|card|id|note)$")
    # We allow some unencrypted metadata if strictly necessary, but prefer everything in enc_data
    # For this secure architecture, 'title' should be inside enc_data to avoid leaking habits.
    
class VaultItemCreate(VaultItemBase):
    enc_data: str = Field(..., description="Base64 encoded encrypted JSON blob")
    iv: str = Field(..., description="Base64 encoded IV")
    auth_tag: Optional[str] = None # Often appended to enc_data, but can be separate

class VaultItemUpdate(BaseModel):
    enc_data: Optional[str] = None
    iv: Optional[str] = None
    auth_tag: Optional[str] = None

class VaultItemResponse(VaultItemBase):
    id: UUID
    user_id: UUID
    enc_data: str
    iv: str
    created_at: datetime
    last_modified: datetime

    class Config:
        from_attributes = True
